apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      containers:
        - name: hello-app
          image: bdodocker25/hello-app:latest  # Use the local Docker image
          ports:
            - containerPort: 3000
